import { Router } from 'express';
import { readFileSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';
import db from '../db/database.js';
import { authenticate } from '../middleware/auth.js';

const router = Router();

// The PSGC dataset (backend/data/ph-locations.json, regenerated by scripts/build-ph-locations.js)
// is static reference data, so it's read once at boot and served from memory — ~600KB resident,
// and no disk or network work on the request path. It's handed out one level at a time rather
// than as a single blob: a province's cities or a city's barangays is a few KB, while the whole
// file would be a 600KB download on every address form.
const DATA_PATH = join(dirname(fileURLToPath(import.meta.url)), '..', 'data', 'ph-locations.json');
const PH = JSON.parse(readFileSync(DATA_PATH, 'utf8'));

// Reference data that only changes when PSGC publishes a new release and the file above is
// regenerated, so it's safe for browsers and any CDN in front of the API to hold onto for a day.
const CACHEABLE = 'public, max-age=86400';

router.get('/provinces', (req, res) => {
  res.set('Cache-Control', CACHEABLE).json({ source: PH.source, generatedAt: PH.generatedAt, provinces: PH.provinces });
});

router.get('/cities', (req, res) => {
  const { province } = req.query;
  if (!province) return res.status(400).json({ error: 'province (PSGC code) is required' });
  res.set('Cache-Control', CACHEABLE).json(PH.cities[province] || []);
});

router.get('/barangays', (req, res) => {
  const { city } = req.query;
  if (!city) return res.status(400).json({ error: 'city (PSGC code) is required' });
  res.set('Cache-Control', CACHEABLE).json(PH.barangays[city] || []);
});

// Streets are the one level PSGC doesn't cover — the Philippines has no national street
// registry to build a dropdown from — so the form falls back to suggesting street names
// HomeLink already has addresses on in that barangay (or, failing that, that city). Only the
// distinct street name comes back: no house numbers, labels, or any hint of who lives there.
router.get('/streets', authenticate, async (req, res) => {
  const { city, barangay } = req.query;
  if (!city?.trim()) return res.status(400).json({ error: 'city is required' });

  let sql = "SELECT DISTINCT street FROM addresses WHERE street <> '' AND lower(city) = lower(?)";
  const params = [city.trim()];
  if (barangay?.trim()) {
    sql += ' AND lower(village) = lower(?)';
    params.push(barangay.trim());
  }
  sql += ' ORDER BY street LIMIT 100';

  const rows = await db.prepare(sql).all(...params);
  res.json(rows.map(r => r.street));
});

export default router;
